name: tf

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  
  

jobs:
  tf:
    name: Run tf
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - run: terraform init
        name: Initialize the terraform
      - run: terraform plan
        name: Planning the tf
      - run: terraform validate
        name: Validating the tf
      - run: terraform apply
        name: Apply the tf
